### ISSUE TITLE
We need help migrating a data array from Tilde

### ISSUE THREAD

**Issue by asd339** [YetiForceCompany/YetiForceCRM#17303] opened 2023-10-16 22:34 UTC
Good afternoon 
We need help migrating a data array from Tilde 

We have a site written on tilde and we really want to integrate everything to you in crm. 

We have had experience in transferring this data to another crm via api. 

How can we do this with you 

We need to link Tilda and your crm.

**Comment by rskrzypczak** [comment] 2023-10-17 05:21
This is not a bug so I am closing the issue.
you need help: https://yetiforce.com/en/company/contact.html

**Closed as completed by rskrzypczak** 2023-10-17 05:21 UTC
