### ISSUE TITLE
[bug] Custom module line items > create entity (invoice) error

### ISSUE THREAD

**Issue by garryatbrighton** [YetiForceCompany/YetiForceCRM#15270] opened 2021-10-05 19:59 UTC
Cannot use Create entity (Create invoice) in workflow as system reporting "Illegal value has been entered for this field type. Field name: currency, Module:".
There is no option to select currency in Mapping (both Mapping itself and mapping/overriding in workflow)

**Comment by rskrzypczak** [comment] 2021-10-06 05:09
I see no error here.
Creating entries for advanced modules with the required entry in the products/services section is possible only through the mapping panel.
All basic fields from this block should be completed.
The invoice module has a currency field, so if you map from a module that does not have one, you cannot create an invoice because not all fields required to create an invoice have been completed.

I am closing this issue, because as I mentioned it is not a bug.
You would most like to set default values for non-existent fields in the base module, but this is an improvement and a different story.
However, when adding a ticket, try to mention as much information about the system as possible and the error you were asked for when creating it;)

**Closed as completed by rskrzypczak** 2021-10-06 05:09 UTC
