### ISSUE TITLE
Open calendar to current day

### ISSUE THREAD

**Issue by antcorro** [YetiForceCompany/YetiForceCRM#15679] opened 2022-01-30 23:49 UTC
### Discussed in https://github.com/YetiForceCompany/YetiForceCRM/discussions/15599

<div type='discussions-op-text'>

<sup>Originally posted by **antcorro** December 30, 2021</sup>
Hello,

when I enter in Calendar and select "Day",  it do not point to current day, but to an arbitrary day.
For what I see it points always to the day after the last day I have visited. Please see the screentogif attached.
Is this a bug? or is there any configuration to point the Day to current day when I open Calendar?

![Peek 30-12-2021 23-06](https://user-images.githubusercontent.com/10244840/147791308-9b18eb7f-b3c4-439d-a9fb-620629b90e18.gif)

Thanks</div>

**Comment by mariuszkrzaczkowski** [comment] 2022-01-31 07:16
Duplicate of #15599

**Closed as completed by mariuszkrzaczkowski** 2022-01-31 07:16 UTC

**Comment by antcorro** [comment] 2022-01-31 09:57
@mariuszkrzaczkowski do you mean that I have to open a new issue not from the discussion? I have opened an Howto discussion, but no solution was suggested. And from the user perspective this behavior is very frustrating and seems like a calendar issue. How can I ask to investigate?

Thanks

**Comment by mariuszkrzaczkowski** [comment] 2022-01-31 10:03
basic information is missing
![github](https://user-images.githubusercontent.com/10198654/151774013-092640cc-b463-42b9-82c0-47c69b4bfc3c.jpg)
