### ISSUE TITLE
[bug] Multiimage | download|  delete | preview | Windows Server 2012 | Windows Server 2019

### ISSUE THREAD

**Issue by reeidgce** [YetiForceCompany/YetiForceCRM#15436] opened 2021-11-14 03:20 UTC
Image and Multimage fields are not working in Windows Severs. Cannot Delete uploaded image or download/preview.
Checked on 3 computers installed in our company. 2 W2019 and 1 W2012.
Further description not necessary, developer might check it if have access to mentioned OS's.
This is significant limitation for corporate users running mentioned operating systems. Other Windows versions are OK

**Comment by mariuszkrzaczkowski** [comment] 2021-11-14 11:44
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/141679407-67f25a12-fb20-4e63-b355-3a5b99389ffb.jpg)

**Comment by mariuszkrzaczkowski** [comment] 2021-11-14 11:47
Duplicate of #15388

**Closed as completed by mariuszkrzaczkowski** 2021-11-14 11:47 UTC
Labels: 🤷‍♂️ MoreInfoRequired
