### ISSUE TITLE
[Solution Suggestion] Handling code customizations

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1752] opened 2015-08-10 16:04 UTC
The following script allows in a very simple and efficient way to customize YetiForceCRM source code and language translations and ensuring code consistency. See also https://www.yetiforce.com/en/developer-documentation/engine/177-loader-and-autoloader-of-files.html

1. Create a directory outside the YetiForceCRM tree in which you want to store the code customizations, for example `/x/y`
2. Install the script `installUpdate.sh` below in the just created directory, that is, `/x/y/installUpdate.sh`  and change the variables `$INSTDIR` to the directory where YetiForceCRM is installed and `$CUSTDIR` to the directory just created
2. Copy the original file you want to modify, for example, `a/b/c.php`, into the directory just created, that is, `/x/y/a/b/c.php` and make your changes to that file
3. Copy the original file you want to modify, for example, `a/b/c.php`, a second time into the directory just created and add the extension `.orig`, that is, `/x/y/a/b/c.php.orig` (this file serves as reference file for future updates) [this third step is not needed / not recommended for language files]
4. run the script `/x/y/installUpdate.sh`

Redo the step 4 each time you change any of your customization filed and each time you install a new version of YetiForceCRM.

The script takes a look at each of the customized files, ensures that the reference file is still identical to the file of the installed YetiForceCRM version and copies it into the custom directory of the YetiForceCRM installation. If the reference and installed files differ, you need to manually adjust your customization to match the newly installed file.

    #!/bin/bash
    
    # YetiForce CRM installation directory
    INSTDIR='/opt/crm2'
    
    # Directory containing customizations
    CUSTDIR='/user/crm2/custom'
    
    # Copy customization files into new installation
    CUSTFILES=$(find $CUSTDIR -name \*.orig -print | sed s/\.orig//g | sed s/custom//g)
    for f in $CUSTFILES
    do
	if [ -e $INSTDIR$f ]; then
            if [ -e $CUSTDIR$f ]; then
                DIFF=$(diff -q -i -E -Z -b -w -B $CUSTDIR$f.orig $INSTDIR$f)
                if [ "$DIFF" == "" ]; then
                    # Create directory, if necessary
                   mkdir -p $(dirname $INSTDIR'/custom'$f)
                   # Copying customization
                   cp -fv $(echo $CUSTDIR$f) $(echo $INSTDIR'/custom'$f)
                   echo Success: Successfully installed $INSTDIR'/custom'$f
               else
                   echo Error: $f is newer than $CUSTDIR$f.orig
               fi
            else
                echo Warning: $f does not exist in customization directory, ignoring
            fi
        else
            echo Warning: $f does not exist in target installation, ignoring
        fi
    done

    LANGFILES=$(find $CUSTDIR'/languages' -name \*.php -print | sed s/custom//g)
    for f in $LANGFILES
    do
        if [ -e $INSTDIR$f ]; then
            if [ -e $CUSTDIR$f ]; then
    			# Create directory, if necessary
    			echo mkdir -p $(dirname $INSTDIR'/custom'$f)
    			# Copying customization
    		    echo cp -fv $(echo $CUSTDIR$f) $(echo $INSTDIR'/custom'$f)
    			echo Success: Successfully installed $INSTDIR'/custom'$f
            else
                echo Warning: $f does not exist in customization directory, ignoring
            fi
        else
            echo Warning: $f does not exist in target installation, ignoring
        fi
    done

**Comment by SkavenKF** [comment] 2015-08-11 19:40
It sound like a good and helpful idea :-)

**Comment by bpabiszczak** [comment] 2015-08-13 06:29
What should we [YetiForce] use it for, though? The only thing missing in YetiForce the possibility to replace every system file [ at the moment it's only possible within the module we are in]. In order to create a comprehensive solution we have to change the way of including files in hundreds of files and add some lines of code to the autoloader. So if you want to come up with a universal solution, then just like I wrote in another issue, it has to be done well and implemented in the system. Your solution is like a detour, it requires executing SH files and perhaps the DIFF library.
I'll repeat my question – for whom is this solution dedicated and what should we do with this issue?

**Comment by diderich** [comment] 2015-08-13 06:54
The solution is for all those that want / have to customize YetiForce so that it suits their needs. If you want those people (and I am convinced the majority of users are at some point changing code tu suit specific business needs) to regularly migrate to new releases, you must give them an opportunity / tool to do so. Otherwise they will either not use YetiForce at all or stick with a specific version (for example my case - I stick with V2.0 because of the numerous changes I made to make the system work in my environment which I don't want to do over and over again).

I am offering this quick fix for those users that want to use it. These are not your employees or you because you own the master code and can change it whenever you want. If nobody sees a need in this quick fix, that's fine my be too. It simply works for me and I am sharing what works for me with the community.

**Comment by bpabiszczak** [comment] 2015-08-13 08:40
1. If you have an idea and some programming knowledge, you also can introduce changes to the engine. If you want to have a universal solution [better than what you offered] it's enough to develop the autoloader and modify including where it was set firmly.

2. I don't know if this is a good place, issues are made to avoid them [someone adds something and we either fix it, add it to the system, or ignore it as incorrect, and after some time the issue is closed]. Maybe you should add it to the mailing list ? Everyone who subscribed will receive it on their emails, and we could close it.

**Closed by bpabiszczak** 2015-08-13 08:40 UTC
Labels: discussion

**Comment by diderich** [comment] 2015-08-13 08:53
I believe it would be a good idea to have a place (blog, wiki, ...) somewhere where such ideas / options could be posted without a) getting lost because the issue is closed and b) which are available to users who weren't on the list when the idea / option was raised?I currently have no idea how this could look like, though.
In the actual issue: From my perspective the challenge / problem of upgrading a highly customized system to a new version is not satisfactorily solved yet (it is partially solved with the custome directory and barely solved with respect to the database). What is the best way of raising that issue so that it will stay pending untill resolved (or discarded, in which way it will be highly unlikely that I will follow-up with release changes as the associated migration effort will be too high).

Claude

**Comment by bpabiszczak** [comment] 2015-08-13 10:50
If that's too much effort for you to do it well in YetiForce [or you don't have sufficient knowledge or time], and at the moment we don't consider it relevant enough or we don't have time to do it now, then there's no point for it to stay pending anywhere. I can add 20 elements that I want in the system daily, and have a few thousands of them after a year, but that's not the point. It's important to add elements that are essential at the moment and the ones we plan to deploy, all the other ones are irrelevant and should be forgotten until they become relevant. 

If this functionality is important for you then you can always pay someone to create it for you and then it can be incorporated in YetiForce.
