### ISSUE TITLE
[bug] Dashboard - Predefined widgets cannot be removed

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#16879] opened 2023-02-10 14:50 UTC
In Dashboard predefined widgets cannot be removed
both stable and dev versions

![Schermata da 2023-02-10 15-48-46](https://user-images.githubusercontent.com/48508691/218121050-984083f3-d7c0-4e03-a029-0695e483d33e.png)

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![Schermata da 2023-02-10 15-45-36](https://user-images.githubusercontent.com/48508691/218121093-1568d47c-fa8e-446b-a050-b016df900cb8.png)

**Comment by apcloic** [comment] 2023-02-11 10:15
Also reported here #16633

**Comment by mariuszkrzaczkowski** [comment] 2023-02-11 11:25
Duplicate of #16633

**Closed as completed by mariuszkrzaczkowski** 2023-02-11 11:25 UTC
