### ISSUE TITLE
Relations between modules

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#20] opened 2014-12-19 08:03 UTC
Depending on the internal processes of a company, different relations between modules are important. For example, I would like to be able to associate a Service with a Lead, Organization, Opportunity and Project. It should be possible to relate any module to any module (using the Arrange Related Types function).

**Comment by bpabiszczak** [comment] 2015-01-26 13:49
Unfortunately, most customers have exactly the same processes. The problem is that we often don’t know how to explain it to a customer. Every sales process should be carried out by an Opportunity, everything what has been sold, should be carried out through a Project. It often happens, that new modules (e.g. cars for insurance companies, Power Generation Point for the energy sector) need to be added in those processes, however the processes are the same, it may lack some marketing or production processes.

Costs should be assigned to processes (marketing, sales, projects, tickets) and there should be a summary on Service Contracts (as it is now). We have written out the processes and we are going to improve and update them. If you want us to change something (we plan to change a lot of things and the processes will change significantly), you would have to explain why you think this process isn’t optimal and how it should be changed.

In the future, we are going to add more tools that will allow to manage all of this from a panel, but it is more complicated than you think, because Vtiger hard-wired it in many places.

I don’t know how I can help you with this issue.

**Closed** 2015-02-03 23:06 UTC
Labels: more info required, question
