### ISSUE TITLE
[Bug] PDF Templates  - cant add any field

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1500] opened 2015-07-13 15:11 UTC
PDF module is not working correctly for many weeks. If you try add a field (let say in invoice template) it simply saving edited document instead of copying such.
Due to fact that there is no other option (commercial or not) this module would need attention

**Comment by bpabiszczak** [comment] 2015-07-14 11:03
1. If you knew about an error and you didn't report it you can only blame yourself that the issue is not fixed yet. 
2. Unfortunately, I don't know what's wrong or how to recreate the error after reading your email.

I'm closing this issue, if you think the error exists and you want us to fix it, follow these steps:

1.Read this article: https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html 
2. Precisely describe what is wrong and how you want it to work correctly, how to recreate the error step by step. 
3. Check your logs for anything that seems wrong: https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html
4. Specify your system version, paste the pdf template, etc. anything that can prove to be useful.

**Closed by bpabiszczak** 2015-07-14 11:03 UTC
