### ISSUE TITLE
[bug] Workflow conditions are not trigerring

### ISSUE THREAD

**Issue by Marshal4582** [YetiForceCompany/YetiForceCRM#15505] opened 2021-12-02 01:29 UTC
I did numerous tests and here is final result of one of certains combination of workflow:
- Only once, when all conditions are met
- Custom Date field: condition "days ago = 1"

The result is that workflow will not trigger 1 day after. It will trigger ONLY if I manually chage date field. 
That is against expected behavior, so I reporting it as a bug.
I am not mmentioning env config etc, as this is failing everywhere

**Comment by rskrzypczak** [comment] 2021-12-02 05:40
This is not a bug.
This is how this functionality works.
The system does not monitor the records all the time, so such conditions are pointless here.
In other words, this type of workflow action is triggered in the same way as "Every time a record is saved (eg. creating, modifying)" with the difference that it will be performed only once.

As I mentioned, this is enhancement, not a bug, so I am closing the issue.

**Closed as completed by rskrzypczak** 2021-12-02 05:40 UTC
Labels: enhancement

**Comment by TonyM15** [comment] 2021-12-02 05:48
Than Workflow name is missleading. Maybe change to "Only once, when all conditions are met (creating, modifying)"
And here is again another reason for changing little bit workflows as per: https://github.com/YetiForceCompany/YetiForceCRM/discussions/15318
If you add to "days" hours, minutes, seconds it will boost WF flexibility enourmously
