### ISSUE TITLE
[bug] Email compose window opened from module is bugged

### ISSUE THREAD

**Issue by mnawrockiht** [YetiForceCompany/YetiForceCRM#14601] opened 2021-04-27 07:24 UTC
### ⁉️ Describe the bug
After clicking on "Send mail" button from any module that has emails related, a window that opens is bugged. Firstly it opens with enormous window size. Secondly, it can't open any lists of CRM records, which is a major setback. It means that clicking either: "Templates", address picking fields (Accounts, Contacts, Employees etc.) or "Select File from CRM" does nothing.

### 🔥 How to trigger the error

![Animation](https://user-images.githubusercontent.com/82452801/116201558-ea407780-a739-11eb-8ab6-fa95d15da2ec.gif)

### 👎 Actual Behavior
Email compose window can't access any modules from CRM.

### 👍 Expected Behavior
Email compose window with the same behaviour as one opened from RoundCube module.

### 👷 Testing
- [✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by mariuszkrzaczkowski** [comment] 2021-04-27 07:26
Duplicate of #13979

**Closed as completed by mariuszkrzaczkowski** 2021-04-27 07:26 UTC
Labels: 🔙 duplicate

**Comment by mnawrockiht** [comment] 2021-04-27 07:57
Yup, the issue is duplicate with mail composer not accessing CRM modules, sorry for that. 
There is no mention in opened issues about the window size of composer. It is not a huge problem, more of an inconvenience, but please address it.
