### ISSUE TITLE
[4.4.0] Relation cause error after changing fields [question]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7715] opened 2018-08-20 09:22 UTC
#### Issue
Look like my Upgrade is corrupted in some way. It is causing an error in my Relation field. I recently made some changed to what field is shown in the Relation. Now it is showing an error that I don't know how to fix. Anyone run into this issue before?

#### Actual Behavior
Error relation, can't view documents.

#### Expected Behavior
Able to view documents and it relation.

#### How to trigger the error
1. Open "Module - Relations" in Admin Setting: /index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&block=2&fieldid=41
2. By default it is Contact. Under Documents relation, change the standard fields to Filename/WWW.
3. Open the Contact. 
4. Error is Display as follow:
![issue - relation errors](https://user-images.githubusercontent.com/1805303/44331976-485b2e00-a4ae-11e8-9dbd-db650977b867.png)
![issue - relation errors 2](https://user-images.githubusercontent.com/1805303/44331978-485b2e00-a4ae-11e8-9ad4-410f2312e98b.png)
![issue - relation errors 3](https://user-images.githubusercontent.com/1805303/44331980-485b2e00-a4ae-11e8-8492-efe7d6c3e31c.png)

`Fatal error: Uncaught Error: Call to a member function isViewable() on boolean in D:\XAMPP\htdocs\modules\Vtiger\models\RelationListView.php:280 Stack trace: #0 D:\XAMPP\htdocs\modules\Vtiger\views\RelatedList.php(115): Vtiger_RelationListView_Model->getHeaders() #1 D:\XAMPP\htdocs\modules\Vtiger\views\Detail.php(481): Vtiger_RelatedList_View->process(Object(App\Request)) #2 [internal function]: Vtiger_Detail_View->showRelatedList(Object(App\Request)) #3 D:\XAMPP\htdocs\app\Controller\ExposeMethod.php(63): call_user_func_array(Array, Array) #4 D:\XAMPP\htdocs\modules\Vtiger\views\Detail.php(155): Vtiger_Detail_View->invokeExposedMethod('showRelatedList', Object(App\Request)) #5 D:\XAMPP\htdocs\include\main\WebUI.php(183): Vtiger_Detail_View->process(Object(App\Request)) #6 D:\XAMPP\htdocs\index.php(25): Vtiger_WebUI->process(Object(App\Request)) #7 {main} thrown in D:\XAMPP\htdocs\modules\Vtiger\models\RelationListView.php on line 280`

The MYSQL is this one I think: 
http://localhost/phpmyadmin/sql.php?db=yetiforce&table=vtiger_cvcolumnlist&goto=db_sql.php&pos=0&is_js_confirmed=0&

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version:  FF61
* Environment name and version: XAMPP
* Operating System and version: Windows

**Comment by ldgbc** [comment] 2018-08-20 09:33
Further investigation it seem that it not related to the folder: D:\XAMPP\htdocs (ie. it not file changes) that cause the error. I restore a htdocs backup but it still have the error. So it must be related to MYSQL (database)? So if I can find where these relationship is stored in the Database, maybe I can then do a comparison and see what causing the issue.

**Comment by vovpff** [comment] 2018-08-20 10:44
@ldgbc after update you  need to start CRON to finish update. But some files for cron was changed and maybe this is cause of problem.

Just for example cron file for 4.3 here root/cron/vtigercron.php
for 4.4. root/cron.php

**Comment by ldgbc** [comment] 2018-08-20 14:04
@vovpff that could be the case, but I been running the CRON many days now. My mistake could be this: Update from v4.3 to v4.4, test the system, seem working fine, started using it.

Realize my search wasn't updating, etc 1 or 2 day later. Notice CRON didn't work yet and realize that changed as you stated from root/cron/vtigercron.php to 4.4. root/cron.php.

Which apparently caused issue with Contact Images too, there is a few issue/comments related to that.

That could be where it corrupted but relations linking, it worked fine but I wanted to changed one of the Field it display, then it got corrupted.

**Comment by vovpff** [comment] 2018-08-20 14:43
@ldgbc I understand what you mean
I just checked and has this:
![image](https://user-images.githubusercontent.com/8545791/44347427-746fb280-a4a0-11e8-90a9-51b9d5d67153.png)
But now I can't change selected columns and sequence can't be changed too

**Comment by vovpff** [comment] 2018-08-20 17:07
@ldgbc gitdev 4.4.27 checked. Looks like works well.
This is local problem after update...

**Comment by ldgbc** [comment] 2018-08-21 00:08
@vovpff I just tested on Stable build: https://gitstable.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&block=2&fieldid=41

Which can't reproduce the error, but at least knowing it not just my XAMPP system that having that issue is a semi-good sign. At this point in time, I am just going to delete the module, create a new using "many to many with separation" as I don't want to delay this issue too long.

**Comment by slawekk87** [comment] 2018-11-19 16:43
@ldgbc  Problem with disapering fields after refresh is fixed in developer version.
I tried to reproduce this issue on 4.4 stable, developer, 4.3 migrated to 4.4 and it works good. 
On screenshot You selected custom field 'File Category Type', what is type of this field and is it working all ok?

Can You provide data from database:
vtiger_relatedlists_fields - rows with fields defined for this relation
vtiger_field - rows with fields used in relation

**Closed** 2018-11-20 14:04 UTC
Labels: MoreInfoRequired

**Comment by z0lo13** [comment] 2019-02-11 16:38
@bpabiszczak 
So When? you will realease the fix for this. How can i repair my stable 4.4.0? I ve added couple new relations and now cant add any fields they dont save in vtiger_relatedlists_fields table

**Comment by mariuszkrzaczkowski** [comment] 2019-02-11 17:10
We are publishing a new version and update package tomorrow
