### ISSUE TITLE
Update 3.1.0 to 3.2.0 - module does not contain default language

### ISSUE THREAD

**Issue by oliverjnash** [YetiForceCompany/YetiForceCRM#3624] opened 2016-10-03 21:29 UTC
Hello,

I'm having an issue updating from 3.1.0 to 3.2.0. Whenever I upload the update package via the module manager it tells me that the "Module does not contain default language (en_us)."

Has anyone else encountered this error?, if so, did you manage to resolve it and how? 

I'm running YetiForce 3.1.0 and accessing it using Safari 10.0. The OS I'm using is MacOS Sierra. 

Many thanks,

Oli

**Comment by noclav** [comment] 2016-10-05 17:53
click on the link for the zip then it will take you to another page with the download button. Do Not Right Click and select save as.

**Comment by bpabiszczak** [comment] 2016-10-06 18:57
Give me a link to a file that you used.

**Comment by oliverjnash** [comment] 2016-10-06 19:17
@noclav - I already tried that :(

@bpabiszczak Here's the link I used - https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x/3.1.0_to_3.2.0/zip

**Comment by bpabiszczak** [comment] 2016-10-06 19:18
What language you use/set in the system?

**Comment by oliverjnash** [comment] 2016-10-06 19:49
@bpabiszczak - en_us is set as the default in the system 
<img width="1387" alt="screen shot 2016-10-06 at 20 49 32" src="https://cloud.githubusercontent.com/assets/22603257/19168086/6801bc78-8c06-11e6-988d-8cccbb513be4.png">

**Comment by oliverjnash** [comment] 2016-11-03 01:28
@bpabiszczak - Could you assist with this? We're desperate to get the system updated to resolve some of the niggling little bugs from the last version. 
I noticed you have labeled this with 'More info required' - but I've provided all the information asked? 

Many thanks

**Comment by paula-w** [comment] 2016-11-04 10:32
This will most likely be fixed in v3.5

**Comment by oliverjnash** [comment] 2016-11-12 02:03
Hi @paula-w 

But surely we still need to update to 3.2 first, then 3.3, and so on before we get to 3.5?

**Comment by bpabiszczak** [comment] 2016-11-13 20:40
Yes. Please read this article: https://yetiforce.com/en/implementer/installation-updates/138-yetiforce-number-system.html

**Comment by oliverjnash** [comment] 2016-12-16 21:51
But like I said, I can't update because it's not working. So how do I get around this?

**Comment by bpabiszczak** [comment] 2016-12-27 14:35
Your problem requires an individual approach. We don’t know what the logs say, we don’t know anything about your server configuration, we don’t know whether or not there were any prior updates with no errors in the logs. The answer to your questions is in the system logs. Somebody has to analyze your logs, and on that basis figure out what the problem is.

You either have to handle it on your own with your programmer, or you can order that analysis from us [https://shop.yetiforce.com/en/17-support].

**Closed by bpabiszczak** 2016-12-27 14:35 UTC
Labels: Subcategory::VerificationRequired
