### ISSUE TITLE
[bug] YF 6.4 - PDFs merge error

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#16663] opened 2022-11-18 09:08 UTC
# 🐞 bug report

PDFs merge error

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

https://user-images.githubusercontent.com/48508691/202664142-128e268e-75ed-48cf-815c-04cdee64004e.mp4

**Comment by mariuszkrzaczkowski** [comment] 2022-11-18 09:20
Duplicate of #16457

**Closed as completed by mariuszkrzaczkowski** 2022-11-18 09:20 UTC
