### ISSUE TITLE
Bug - Sales Order

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3099] opened 2016-06-07 18:00 UTC
When I make the sales process , service orders do not inherit the product or service from the Quote. I did the tests in the current version .

https://gitdeveloper.yetiforce.com

1- 
![image](https://cloud.githubusercontent.com/assets/3030997/15868927/464dcbee-2cc0-11e6-9509-fb68b0caa559.png)

![image](https://cloud.githubusercontent.com/assets/3030997/15868942/52e39640-2cc0-11e6-80c1-74783ebb3b60.png)

2-
![image](https://cloud.githubusercontent.com/assets/3030997/15868961/6258c2b2-2cc0-11e6-82ea-c0743c62d34b.png)

3-
![image](https://cloud.githubusercontent.com/assets/3030997/15868978/83b73f88-2cc0-11e6-91dd-e3c2a9ae47ab.png)

4-
![image](https://cloud.githubusercontent.com/assets/3030997/15868969/6e272548-2cc0-11e6-8027-603dace1db81.png)

Thanks

**Comment by dextras** [comment] 2016-06-08 20:24
This is not a bug. It is just not the way you should do it. 

First you should go to Admin -> Standard Modules -> Mapping.

There you define a new mapping from Quotes to Invoices.
![image](https://cloud.githubusercontent.com/assets/7486027/15909443/b33b81b8-2dc6-11e6-9657-2855501cad86.png)

And:

![image](https://cloud.githubusercontent.com/assets/7486027/15909463/cbac0560-2dc6-11e6-868b-561abe465cda.png)

![image](https://cloud.githubusercontent.com/assets/7486027/15909506/f1f07bb6-2dc6-11e6-9719-6822e18aaf7c.png)
etc...

Then after creating a quote you will see an additional icon in the right upper corner (the first one on the left in the bottom row):
![image](https://cloud.githubusercontent.com/assets/7486027/15909628/6bfa3c6c-2dc7-11e6-829e-77395c4c7d3d.png)

When you click on it you will be able to generate one record based on another (in this example it will be Invoice from Quote).
Hope it helps. If you need more detailed description let me know.

**Closed** 2016-06-08 20:27 UTC

**Comment by skramanzia** [comment] 2016-06-08 20:55
Great!!, thanks you bpabiszczak!! you are the best!.

 Do you know if there is any way to change the default columns of PDF?


![image](https://cloud.githubusercontent.com/assets/3030997/15910532/aae097bc-2da1-11e6-86bd-30b9c353a507.png)


Thanks in advanced

**Comment by bpabiszczak** [comment] 2016-06-08 20:56
dextras help you, not me :]

**Comment by dextras** [comment] 2016-06-08 20:56
I just wanted to write it ;)

**Comment by dextras** [comment] 2016-06-08 20:59
@skramanzia  well... I do know ;) It requires some programming skills though. What I did is I created a new function based on the special pdf function in /modules/vtiger/pdf/specialfunctions/ProductsTableNew.php. 

Maybe there is some other way? @bpabiszczak ?

**Comment by bpabiszczak** [comment] 2016-06-08 20:59
PDF generates the same column which are set in the module. For sure from the database and the special function you can change it.

**Comment by bpabiszczak** [comment] 2016-06-08 21:00
If you pay, we will add it to the configuration fields: P

**Comment by dextras** [comment] 2016-06-08 21:01
@bpabiszczak makes sense :)
