### ISSUE TITLE
[bug] Maybe bug - hidden related list

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11397] opened 2019-09-03 22:26 UTC
Dunno how it come but related list is hidden by default. Need to click search magnifier to get is visible. See attached gif. Did I missed something?
![hid_re_records](https://user-images.githubusercontent.com/6852348/64212747-903fce00-ced4-11e9-9400-ec1b5fdff229.gif)

**Comment by rskrzypczak** [comment] 2020-02-20 08:12
This issue most likely doesn't exist anymore.
It's hard to point you to a specific solution because lately we've introduced a number of modifications regarding relations.
Apart from that, the Reservations module by default doesn't have any relations with Calendar so this relation was most likely hard coded, so the cause might be something else.
I'm closing the issue.
If you can duplicate this bug on the gitdeveloper environment you can reopen the issue.

**Closed by rskrzypczak** 2020-02-20 08:12 UTC
Labels: ❔ question
