### ISSUE TITLE
Feature Request: Options for opening side menus

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5610] opened 2017-12-01 21:50 UTC
Hi,
it would be good if we were able to set the behavior of how the side menus work. It can be a little annoying the way they open on hover as it makes the system feel 'shakey'. I know there is an option to set the menu in preferences as open (which is great) but I also like having just the icons as it gives more space on screen. 

A 'nice to have' would be the ability to have the menus open/slide out on Click
It would also be good to have the option to set it to open over the top of the current page - rather than push it to the right.

**Comment by ezbank** [comment] 2017-12-03 07:49
#3322

**Comment by ezbank** [comment] 2017-12-03 07:50
Duplicate of #3322

**Comment by PercyP** [comment] 2017-12-03 10:39
Hi @ezbank,

does that new menu layout still exist? It looks good. 
I am happy with existing menu, but just prefer to open the menu items on click rather than on hover as it gets annoying as keeps opening the menus accidentally when mouse moves too close. I am hoping I can just change some string in the code somewhere to achieve this

**Comment by migoi** [comment] 2017-12-04 10:07
I've modified the default skin to have such kind of navigation.

**Comment by PercyP** [comment] 2017-12-04 10:32
@migoi 
ah I see. I am playing with the default skin too. I only really want to have the menus ope up on click rather than on hover - did you manage to do that?

**Comment by migoi** [comment] 2017-12-04 10:41
yes
![navigation](https://user-images.githubusercontent.com/25817094/33548610-fd1e4478-d8e7-11e7-840f-f6d91d2726d5.gif)

**Comment by ezbank** [comment] 2017-12-04 10:45
@migoi nice :)), can you shared it

**Comment by PercyP** [comment] 2017-12-04 10:54
@migoi 
thats brilliant! How did you create it? Can you share it with yetiforce team?

**Comment by migoi** [comment] 2017-12-04 10:57
yes / no / maybe

sure i can share it, but that's more a "hack" than an extension to the code, since some basic files need modification and those will break the other themes.

**Comment by bpabiszczak** [comment] 2017-12-11 22:18
https://github.com/YetiForceCompany/YetiForceCRM/issues/3322

**Closed** 2017-12-11 22:17 UTC
Labels: Category::Enhancement
