### ISSUE TITLE
Cannot attach file to email[bug] 

### ISSUE THREAD

**Issue by 07litra** [YetiForceCompany/YetiForceCRM#15089] opened 2021-08-20 08:52 UTC
# 🐞 bug report

### ⁉️ Describe the bug

I am having trouble sending email whith  attaching a file.
File is not attached.

### 🔥 How to trigger the error

https://user-images.githubusercontent.com/81667454/130206012-51a26c68-9a82-4e52-b20a-15941d7d134b.mp4

1. Go to **documents**
2. Click on **sent document via mail**
3. See error - no attachment 
4. button " select a file from CRM" is disabled

### 👷 Testing

this function is 
- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com
this function is not enabled in demo 

### 📷 Screenshot of configuration

![ConfReport](https://user-images.githubusercontent.com/81667454/130205726-a6a594eb-665c-4547-baa1-ace8a904fbc5.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |YetiForce CRM 6.2 Service Pack v2 
| Web server (name and version)       |     nginx/1.14.2
| PHP                                 |       PHP 7.3.29         |
| Browser (name and version)          |  Google Chrome  92.0.4515.159               |
| Operating System (name and version) |  Windows 10 Pro 21H1              |
| Database (name and version)         |   yetiforce     mysql  Ver 15.1 Distrib 10.3.29-MariaDB,        |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment] 2021-08-20 08:55
Duplicate of #13979

**Closed as completed by mariuszkrzaczkowski** 2021-08-20 08:55 UTC

**Comment by 07litra** [comment] 2021-08-20 09:28
#13979 was opened on 28 Dec 2020 and still open .

**Comment by mariuszkrzaczkowski** [comment] 2021-08-20 09:36
this is not a simple problem to solve
