### ISSUE TITLE
Logic not transferring to Customer Portal

### ISSUE THREAD

**Issue by bfeddes** [YetiForceCompany/YetiForceCRM#16950] opened 2023-03-09 17:25 UTC
Whenever I go to edit the fields for our portal (Webservice Premium), and want to set a default value, the default value does not apply in the Customer Portal. However, when I want to disable/enable fields, that does apply in the Customer Portal. The issue for this is that in the Ticket module, I want the default "Assigned To:" value to be our Support Group. However, even when I make that the default value and it says it was applied, when opening a ticket in the portal, the default value is not applied.

To trigger this error, all I did was simply go to Software Configuration > Standard modules > Edit fields > portal (Webservice Premium) > Tickets > Assigned To > Checked the Default value box. Even when closing out of the field configuration and returning, it says that the default value that I selected, in this case, Support Group, has been applied. The problem remains that when I create a ticket in the portal, that this default value is in fact not applied. This bug also persists in all other modules as well, not just Tickets.

Go to 'Software Configuration > Edit fields > Tickets > portal (Webservice Premium)'
Click on 'Assigned To'
Check the box 'Default Value'
Select the User/Group you want it to be assigned to by default
Save
Go to your customer portal
Create a Ticket
Look at who the Ticket is assigned to
In my case, it was assigned to Administrator, while it should have been assigned to Support Group.
See error
Here is the configuration:
![yeti1](https://user-images.githubusercontent.com/112420814/220410122-c9e1a3a0-ae4e-4fe5-bc97-1782e9238de1.PNG)

Here is the result:
![issuee](https://user-images.githubusercontent.com/112420814/220410255-6cd7c05e-eecb-4c6b-bb8a-b486e0bbb150.PNG)

As you can see, it is by default assigned to Administrator, while it should be assigned to Support Group. This issue has been persisting for over a week and I was hoping to get a solution to this. Someone viewed this bug and marked it as closed, but this issue is still persisting. I made sure the Support Group was added to the Tickets module already. I am wondering if there is some error with how the customer portal or our yetiforce was configured that would be causing this issue and if anyone knew any solutions to it.

Adding on, the default values do not apply to any selected fields in the customer portal. I issued default values for ticket name, assigned to, etc, none applied. However, if I disable a field or change its visibility, those changes do apply, the issue is only with assigning defaults.

**Comment by mariuszkrzaczkowski** [comment] 2023-03-09 19:21
if the paid functionality does not work as intended, report it to sla@yetiforce.com

**Comment by ghost** [comment] 2023-03-26 22:20
If I'm correct, your problem is within the step of being assigned to Administrator, is that it?

**Comment by mariuszkrzaczkowski** [comment] 2023-03-27 06:53
> If I'm correct, your problem is within the step of being assigned to Administrator, is that it?

As far as I know, we don't have a report of this bug on sla

**Closed as completed** 2024-09-12 08:59 UTC
