### ISSUE TITLE
How to share records correctly? [Question]

### ISSUE THREAD

**Issue by prashanth1k** [YetiForceCompany/YetiForceCRM#6276] opened 2018-03-06 17:35 UTC
#### Issue
How do you share records in the system?

- I have created a new entity called 'Policy'.
   Made the entity 'Private'.

- Defined a new structure
     Account > John Doe & Company

#### Actual Behavior
User sees records assigned to her, but not the records assigned to the role tagged to user.

#### Expected Behavior
If I assign any user to the role, do they not see all 'Policy' records belonging to 'John Doe & Company'?

#### Your Environment
* YetiForce Version used: 4.3.0
* Browser name and version: Chrome 64.0.3282
* Environment name and version: Shared Hosting

#Question - Record Sharing

**Comment by prashanth1k** [comment] 2018-03-07 16:01
From vTiger documentation, I figured out the following:

1. 'Private' module access will disable record share among people with same role (the above question stays corrected)
2. I cannot turn to 'Public' or have admin users since there are only certain groups that need to share records.

So - the design changed - 

I created 'groups' (e.g. Critical Policy Share Group) and included all roles & subordinates that need to share data (peers, managers, reportees). Now my group has 'Manager A', 'Manager B', 'Rep A' roles.

Assigned Policy records (changed 'Assigned To' field) to 'Critical Policy Share Group'.

My expectation is now to see Policy records by 'Manager A' and 'Manager B' roles.
But, 'Manager A' continues to see records that she created. So does Manager B.

How is that visibility of records are being driven (seemingly) out of 'created_user_id' instead of 'assigned_user_id' as expected? Note that Policy is a custom entity.

**Comment by prashanth1k** [comment] 2018-03-10 02:08
Can anyone help? This is preventing us from deploying what can be a promising application in a new domain (at least here - for insurance agencies).

- We need to enable sharing of Policy records across users belonging to same department .
- Users (except admin) should not have access to change group (but can reassign to other users in the group)

I have tried assigning to groups, users, and sharing through advanced sharing, but could not find out how it can be done.

**Comment by prashanth1k** [comment] 2018-03-13 15:26
@mariuszkrzaczkowski and others.
Is there any way to announce a bounty to solve this for us?

**Comment by bpabiszczak** [comment] 2018-03-13 15:32
We will help you tomorrow.

**Comment by prashanth1k** [comment] 2018-03-13 16:53
Meanwhile I also applied the fix at https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.3.0/SharingPrivilegesFix.zip.

Not sure whether it is the right thing to do, but the issue persists. Creator can see records, but not assigned to.

**Comment by KatarzynaUlichnowska** [comment] 2018-03-14 09:32
The problem is that under a given word [e.g. public/private] users can understand other functionalities in CRM. I will try to describe it simply.

If you want to manage permissions in the module, then you should do it [here ](https://gitstable.yetiforce.com/index.php?module=SharingAccess&parent=Settings&view=Index&block=1&fieldid=5)and set the module as private.
From that moment, every user sees "Only his/her own" records.
To give the user permissions to a record that does not belong to him/her, we use this [tool](https://gitstable.yetiforce.com/index.php?module=SharingAccess&parent=Settings&view=Index&block=1&fieldid=5) and we use the tool: "Advanced sharing rules".
If the record belongs to a group, then we grant permissions [here](https://gitstable.yetiforce.com/index.php?module=Groups&parent=Settings&view=List&block=1&fieldid=4). 
If a record is assigned to a user, then it does not matter what you have set in the group. Permissions set on a group work only for the record assigned to this group.

The fix for SharingPrivilegesFix.zip applies to something completely different.

The vTiger documentation does not apply here, we have introduced 20,000 changes compared to vTiger, everything works differently there than in our system, especially permissions.

**Closed by KatarzynaUlichnowska** 2018-03-14 09:32 UTC
Labels: question
