### ISSUE TITLE
[Docker] Install roundcube on the docker

### ISSUE THREAD

**Issue by acrobatix** [YetiForceCompany/YetiForceCRM#13344] opened 2020-07-27 11:54 UTC
# 🐞 bug report

### ⁉️ Describe the bug

With the Docker stable as the developp version, I can't install the module roundcube. When I click on the installation button, the page is refresh but the module isn't be installed. I tested to copy manually the lib_roundcube, it doesn't work also. 

### 🔥 How to trigger the error

1. Modules - Installation
2. Download library

### 👨‍💻️ Command to launch docker
docker run --name Yetiforce-stable -d -p 8090:80 yetiforce/yetiforcecrm

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

![Capture](https://user-images.githubusercontent.com/6108719/88537575-1c3b7680-d00e-11ea-86af-beb83074d984.PNG)

- /var/www/html/cache/logs/system.log
No file
- /var/www/html/cache/logs/errors.log
No File
- /var/www/html/cache/logs/cron.log
[cron.log](https://github.com/YetiForceCompany/YetiForceCRM/files/4981827/cron.log)

- /var/log/nginx/error.log
Empty
- /var/log/nginx/localhost_error.log
[localhost_error.log](https://github.com/YetiForceCompany/YetiForceCRM/files/4981828/localhost_error.log)

- /var/log/nginx/php{php version}-fpm.log
[php7.3-fpm.log](https://github.com/YetiForceCompany/YetiForceCRM/files/4981829/php7.3-fpm.log)

- /var/log/mysql/error.log
Empty
### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |5.3.40 and 5.3.127
| Web server (name and version)       |  Nginx 1.14.2               |
| PHP                                 |        7.3.17        |
| Browser (name and version)          |        Chrome   84.0     |
| Operating System (name and version) |     Docker          |
| Database (name and version)         |       MariaDB 10.3.22          |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment] 2020-07-28 05:42
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/8fedca680b451b364e609605d2e290fbc67b6dc9

**Closed as completed by mariuszkrzaczkowski** 2020-07-28 05:42 UTC
Labels: Docker

**Comment by iceghostx** [comment] 2020-07-30 16:12
I have this same problem in Ubuntu 20.04 and YF latest version on a clean server.
To configure email, system says
"Could not find required roundcube library. Some features were disabled. Go to Modules – Installation to download."

In modules - Installation, I can click download library but it doesn't do anything. I can also download the library and "install from file". If I do that, the file does download but when it is then installed, it throws up this error:

Failed
Module does not contain default language (en-US).

I think the team have done a great job putting such a complex piece of software together but these essential functions (like email) should just work  - and when they dont, it really lets the whole project down.

I have seen this error pop up a lot but didnt find a solution. Can we get a fix?

**Comment by mariuszkrzaczkowski** [comment] 2020-07-31 05:58
> I have this same problem in Ubuntu 20.04 and YF latest version on a clean server.
> To configure email, system says
> "Could not find required roundcube library. Some features were disabled. Go to Modules – Installation to download."

This message can be caused by many errors, e.g.
- wrong server configuration,
- communication problem with github server
- the development version requires configuration changes

> In modules - Installation, I can click download library but it doesn't do anything. I can also download the library and "install from file". If I do that, the file does download but when it is then installed, it throws up this error:
> 
> Failed
> Module does not contain default language (en-US).

roundcube cannot be installed like this
this is not an installation module,
if you have a problem, upload the zip file and at this address:  cache/upload/lib_roundcube.zip
and click in the download / install panel

> I think the team have done a great job putting such a complex piece of software together but these essential functions (like email) should just work - and when they dont, it really lets the whole project down.

It works for all our clients, if we see problems with it in our clients, they usually result from incorrect server configuration, after the improvement everything works fine

> I have seen this error pop up a lot but didnt find a solution. Can we get a fix?
