### ISSUE TITLE
Error when creating a new activity

### ISSUE THREAD

**Issue by averied** [YetiForceCompany/YetiForceCRM#15260] opened 2021-10-04 14:26 UTC
I'm in leads, and I create a new activity, there is an error, so the loading animation is looping forever.

![image](https://user-images.githubusercontent.com/10140930/135868970-a61b1d51-182e-4a08-b0cd-156c65428636.png)
![image](https://user-images.githubusercontent.com/10140930/135869103-573ba345-fc2a-4ed7-9076-faed653fdf6b.png)

My system is Windows Server 2019 IIS web server
Yetiforce 4.4

The problem is not present in gitstable or gitdeveloper

I think from the screenshots I've sent, the module with problems is prety clear.. Any ideas on what to check?

**Comment by mariuszkrzaczkowski** [comment] 2021-10-04 18:25
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/135904237-4e042e6a-d7f9-4cd5-93c8-ee6ef876bcfb.jpg)

**Comment by rskrzypczak** [comment] 2021-10-05 15:05
I am closing this issue because the error does not exist in the current version of the system.

By the way, I'm shooting that the error is caused by the date format.
If you set the standard date format in the user settings, the problem will probably disappear.
Nevertheless, the best solution to get rid of the problem is to update the system :)

**Closed as completed by rskrzypczak** 2021-10-05 15:05 UTC
Labels: ❌ ignored

**Comment by averied** [comment] 2021-10-06 08:14
So the user having to change the date format is not a bug? when was this fixed? This a fresh installation from last week. You see.. the package I downloaded is YetiForceCRM-6.2.0-complete.zip

However, the installation says it's 4.4, so I don't really understand what's going on here.

![image](https://user-images.githubusercontent.com/10140930/136166221-3ca5bcf5-843f-4bc0-9e48-189ceae81984.png)

**Comment by rskrzypczak** [comment] 2021-10-06 08:35
Install the latest service pack and check if the error persists. (https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/6.2.0)

**Comment by averied** [comment] 2021-10-06 08:52
OK.. I downloaded package 6.2.0_ServicePack_v4 and extracted on top of my installation. The issue is solved, thanks!

In my opinion, it's a bit confusing when I download a package called "YetiForceCRM-6.2.0-complete", and after installation I get version 4.4, but ok!
