### ISSUE TITLE
[bug] Yetiforce Portal 2 can't connect to the Yetiforce CRM during the installation wizard --> from #15002

### ISSUE THREAD

**Issue by guanchgonzalez** [YetiForceCompany/YetiForceCRM#15030] opened 2021-08-03 08:02 UTC
Firstible, we don't use the Limit directive, due is depecated in last versions of Apache. Instead of we use "AllowMethods" directive:

`<IfModule mod_ssl.c>
   <VirtualHost *:443>
      DocumentRoot /var/www/YetiForceCRM/public_html
      ServerName yetiforcecrm.talecsystem.com
      <Directory /var/www/YetiForceCRM/public_html>
         AllowMethods GET POST PUT OPTIONS PATCH PROPFIND REPORT LOCK DELETE COPY MOVE
         Require all granted
         AllowOverride All
      </Directory>
      ErrorLog /var/log/httpd/YetiForceCRM/error.log
      CustomLog /var/log/httpd/YetiForceCRM/access.log combined
. . .`

In the other hand, as we told you 7 days ago, you suffer the same issue in your demos.

If you check your access.log you can find several request respoonding with an 405 HTML errors for the same methods, while the rest of the request to other routes give a 200 OK response. You should inspect internally your code. The first failure appears during the YetiPortal2 Installation Wizard execution, but is not the only one.

**Comment by mariuszkrzaczkowski** [comment] 2021-08-03 08:44
Duplicate of #15002

**Closed as completed by mariuszkrzaczkowski** 2021-08-03 08:44 UTC
Labels: 🔙 duplicate
