### ISSUE TITLE
Quotes creating pdf

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1318] opened 2015-07-03 06:35 UTC
When I create a pfd in list view, then created pdf has "unstranslated" special funcions like  "#Contacts_email#. No data in the table header

![Error trigger](https://cloud.githubusercontent.com/assets/3193498/8493709/5220a798-215e-11e5-81f1-19de9157d2f4.png)

![PDF](https://cloud.githubusercontent.com/assets/3193498/8493723/7d316288-215e-11e5-9521-0a2f25a52c0a.png)

**Comment by MaciejStencel** [comment] 2015-07-03 14:39
First red box was fixed by removing from template reference to contacts record. This field was removed in earlier revision.

Second problem with blank fields is caused by buggy windows pdf application. Both inside webbrowser and using Adobe Reader printed pdf is renderred correctly.

**Closed by MaciejStencel** 2015-07-03 14:39 UTC
Labels: normal priority bug
