### ISSUE TITLE
When creating a new event, the 'Status' menu is grayed out and can't be changed.

### ISSUE THREAD

**Issue by lamontef** [YetiForceCompany/YetiForceCRM#3402] opened 2016-08-23 06:48 UTC
#### Issue
When creating a new event, the 'Status' menu is grayed out and can't be changed.

#### Expected Behavior
When creating a new call, I would like to be able to mark the call completed immediately, and have access to a follow-up date and description. I don't know if the feature is new in vTiger 6.5, but I've seen that if I mark a call as completed, a new date field appears to enter a follow-up on date. It would be ideal to have a text field so the user can enter in what they will be discussing on the follow-up call. The follow-up call then becomes a new event for the user on the selected date. In the gif below you'll also see that in the Create Event the Day on the horizontal 'calendar' are one off.

#### How to trigger the error

![yetileadissue](https://cloud.githubusercontent.com/assets/1053900/17881246/e62c1ae2-68d1-11e6-92cd-dfcf75f4fa37.gif)

#### Your Environment

* YetiForce Version used: 3.1.1008
* Browser name and version: Mac Chrome Canary - 54.0.2835.0
* Environment name and version: 
* Operating System and version: Mac OS 10.11.6

**Comment by lamontef** [comment] 2016-08-26 09:03
Hi, this has been categorized as 'Question', is there clarification needed from me? This should really be listed as a bug as it doesn't allow for setting the proper classification of meetings or calls (planned, completed, postponed, etc.). The follow-up date and notes would be nice and are in vTiger, as noted, but if the 'Status' field can be fixed, I can use the system, as it is, I can not...

**Comment by bpabiszczak** [comment] 2016-08-26 11:00
People tell us at least a few times a week that just one thing is stopping them from switching to YetiForce :]

It was labeled as „Question”, because we have to explain how this mechanism works. It's not a bug.

The mechanism works in such a way, that the stratus is set automatically upon save, when we add the calendar entry then we can mark it as completed, canceled, postponed.

It was labeled as „Enhancement” because one of our clients asked us to add the option to close it right at the stage of creating calendar entry.

**Comment by lamontef** [comment] 2016-08-26 17:26
The issue is that if I am creating an event, the status is set to what I've set as the default for each user and it can't be changed at the time of creating the event. Currently, I have it set to 'completed' as my default, so that the bulk of what I'll be doing in a day, making phone calls, is set properly. But if I'm going to set up a demonstration or a meeting, the status will be wrong. I can't have my sales guys go through the process of planning a call with a 'planned' event, then have to go back and close it. Even though it's just adding a couple of steps to the process and maybe 30 seconds to the workflow, if you add that up across a day of 25 or 50 phone calls, it's a big chunk of time that we are going to lose due to a drop down menu that's not active.

The best way I've found to do calls (from doing sales work for over 30 years) is to determine who to call (which could be a follow-up listed in the days events or it could be a random lead in the system), check the history and if this is a follow up, see what was discussed last time and any notes for the new call, then make the call. When the call is over, log the call with relevant notes and set the next follow up date (every call will require a follow-up, unless the call ends with the individual telling me to never call again, then that note will need to be added and the 'ok to call' status changed) and add notes for what will be discussed, and then move on to the next call.

The problem is, the status can't be changed, even though I have multiple options in that status picklist. It might not be a bug, but it's limiting. As mentioned in my first post, in looking at vTiger 6.5, which is what the second part of the animation is, it works close to what would be ideal, it lets me choose the status, and if I mark it as completed (held in their case), I also get a new field to set the follow-up date. What would be ideal is a text field to add notes to the follow-up.

**Comment by nic86** [comment] 2016-08-27 16:08
you can use the related event field (full form) to connect multiple successive calls

![schermata da 2016-08-27 18 00 47](https://cloud.githubusercontent.com/assets/18703633/18028476/dcea167a-6c80-11e6-9d87-153c963ba584.png)

**Comment by lamontef** [comment] 2016-08-28 18:14
Hey Nic86, thank you for the suggestion, that method will work very well for the follow-ups. I appreciate the input.

**Closed** 2016-09-05 09:49 UTC
Labels: Category::Enhancement

**Comment by bpabiszczak** [comment] 2016-09-12 18:47
https://github.com/YetiForceCompany/YetiForceCRM/commit/3833283434c49a6d453046bf3738bd6d5fd4847a

**Comment by lamontef** [comment] 2016-11-11 18:13
Quick follow-up on this, what conditions must be met for 'Save & Close' button to be visable and active? When I select a Lead, click 'Add Event' and get the quick entry dialog up, I see the button for a very brief period and then it disappears. I looked at the code and see conditions, which I never seem to be meeting, so the button is never active.

Thanks,
