### ISSUE TITLE
Records access and module access is broken

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#5238] opened 2017-09-21 07:29 UTC
Module access set as private, but NEW_USER see all records in list view.
Also, the access rules to the module do not work if the group is specified.
<img src="https://image.ibb.co/eqwjB5/Untitled_2.jpg">

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment] 2017-11-10 10:27
Unfortunately, this description isn’t sufficient. The fact that the new user can see that might result from various different configurations, you only sent us one screenshot and unfortunately, we would need more to see the entire system configuration. If the user’s profile has an option in the Special Access module enabled then he can see everything regardless of the configuration, and there might be many more cases similar to that. We’re closing this issue, if you want to post a short video that shows the whole system configuration then we can verify it. You can also describe step by step what you change and configure, then we could try to follow your steps and check it.

**Comment by ezbank** [comment] 2017-12-02 03:45
![1a](https://user-images.githubusercontent.com/19627226/33511484-eff3b134-d74d-11e7-979f-6ad5caa7fa65.png)
![2a](https://user-images.githubusercontent.com/19627226/33511485-f0251558-d74d-11e7-9797-76a9a45e2ba2.png)
![3a](https://user-images.githubusercontent.com/19627226/33511486-f05695c4-d74d-11e7-9c74-b3b29874aec7.png)

**Comment by bpabiszczak** [comment] 2017-12-14 07:35
From what I see in the screenshots you granted the user permissions and that’s why he can see records in the module. So I don’t think this is an error, I just tested it and in my opinion it’s working as intended. 
Second of all, the permissions are multidimensional, this means that there are many panels where you can add permissions for the records list, eg  https://gitdeveloper.yetiforce.com/index.php?module=GlobalPermission&parent=Settings&view=Index&block=1&fieldid=54 that’s why it would be better if you could record a gif from the very beginning [creating a user] to the very end, so that we understand what you changed in the system.

**Closed by bpabiszczak** 2017-12-14 07:35 UTC
Labels: Subcategory::VerificationRequired

**Comment by bpabiszczak** [comment] 2017-12-14 07:51
On the gitdeveloper version the data generator checks the private checkbox by default, when this is checked it makes it impossible to open a record because the record becomes private and only people with proper permissions can access it. This mechanism is not completely finished yet so don’t use that in your own production version of the system.

**Comment by ezbank** [comment] 2017-12-14 10:09
@bpabiszczak At the moment, Module access setting have error (gitdev ver. 4.2.640) and i cant show to you gif.
[BUG]
![bug user](https://user-images.githubusercontent.com/19627226/33986815-54ce6610-e0f1-11e7-9ad2-fbbe0db95244.gif)

**Comment by ezbank** [comment] 2017-12-14 10:51
![bug user](https://user-images.githubusercontent.com/19627226/33987546-d99f94ac-e0f3-11e7-9301-792ccc02255e.gif)

**Comment by mariuszkrzaczkowski** [comment] 2017-12-14 10:59
you are testing changes on version 4.2.640 and this has been fixed in 4.2.644 
https://github.com/YetiForceCompany/YetiForceCRM/commit/985d764429b77f67b459b43d5c288409d93e5ceb#diff-971490f6c5113b833bb3ffb69827ac93R3

**Comment by ezbank** [comment] 2017-12-15 07:09
Although it was set up in the access module, but users Sales did not see the lead of users Demo.

![bug user](https://user-images.githubusercontent.com/19627226/34030905-837145fe-e1a1-11e7-95cf-9d3872002051.gif)
