### ISSUE TITLE
[BUG] Print PDF template shows report of selected entry

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1801] opened 2015-08-16 18:50 UTC
I'd like to print project tasks for selected project.
I created project, milestone and tasks  ->  https://gitdeveloper.yetiforce.com/index.php?module=Project&view=Detail&record=109
created report -> https://gitdeveloper.yetiforce.com/index.php?module=OSSPdf&view=Detail&record=114
created PDF template with report -> https://gitdeveloper.yetiforce.com/index.php?module=Reports&view=Detail&record=26

after select my PDF in project detail view i've got this:

```
Database ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yetiforce1_dev.vtiger_reptmptbl_555d0d9ff6e63c3539378220' doesn't exist

Query: select DISTINCT vtiger_projecttask.projecttask_no AS 'ProjectTask__Project__Task__No', vtiger_projecttask.projecttaskname AS 'ProjectTask__Project__Task__Name', vtiger_projecttask.projecttasktype AS 'ProjectTask__Type', vtiger_projecttask.targetenddate AS 'ProjectTask__Target__End__Date' from vtiger_project inner join vtiger_crmentity on vtiger_crmentity.crmid=vtiger_project.projectid left join vtiger_groups on vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_users on vtiger_users.id = vtiger_crmentity.smownerid left join vtiger_reptmptbl_555d0d9ff6e63c3539378220 as vtiger_projecttask on vtiger_projecttask.projectid=vtiger_project.projectid left join vtiger_crmentity as vtiger_crmentityProjectTask on vtiger_crmentityProjectTask.crmid = vtiger_projecttask.projecttaskid AND vtiger_crmentityProjectTask.deleted=0 WHERE vtiger_project.projectid > 0  AND vtiger_crmentity.deleted=0  order by `ProjectTask__Target__End__Date` ASC
#0  PearDatabase->checkError() called at [/home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/include/database/PearDatabase.php:326]
#1  PearDatabase->query() called at [/home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/OSSPdf/models/Record.php:614]
#2  OSSPdf_Record_Model->ReportToPdf() called at [/home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/OSSPdf/PDFExport.php:124]
#3  find_report_tags() called at [/home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/OSSPdf/PDFExport.php:188]
#4  TakeContent() called at [/home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/OSSPdf/PDFExport.php:816]
#5  include(/home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/OSSPdf/PDFExport.php) called at [/home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/OSSPdf/actions/OSSPdfAjax.php:45]
#6  OSSPdf_OSSPdfAjax_Action->process() called at [/home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/include/main/WebUI.php:220]
#7  Vtiger_WebUI->process() called at [/home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/index.php:25]
```

anyway - is my way ok with this print template ?

**Comment by florek41** [comment] 2015-08-18 05:38
What you need to know ?

Bug is recreated, again, on gitdeveloper.

**Comment by bpabiszczak** [comment] 2015-08-18 11:09
Don't worry, we'll ask the questions when the time comes. We have to check and verify it. The problem is that the PDF module will be redesigned, so we don't necessarily want to deal with it ;)

**Comment by bpabiszczak** [comment] 2015-09-07 11:39
The module is being rewritten [https://github.com/YetiForceCompany/YetiForceCRM/tree/lab-pdf]
I'm closing the issue because the new module will work in a different way and this error won't occur [if any errors are found, you will have to open a new issue]

**Closed by bpabiszczak** 2015-09-07 11:39 UTC
Labels: Label::MoreInfoRequired
