### ISSUE TITLE
[bug] Unable to delete or replace profile picture

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#15305] opened 2021-10-13 00:55 UTC
When you go to profile and try to delete a profile picture, nothing happens. There is no way to upload another profile picture if the old one is not removed. 

When is this going to be fixed? This issue has been there forever. Just installed 6.2 and the issue is still there.

**Comment by rskrzypczak** [comment] 2021-10-13 04:50
I see no error here.
Did you test it on a demo version?

I suppose the problem may be with your server configuration.
Provide more information.

**Comment by mariuszkrzaczkowski** [comment] 2021-10-13 05:47
![github](https://user-images.githubusercontent.com/10198654/137074397-f44e5795-109c-4e85-9530-079e180ef36a.jpg)

**Comment by acoolov** [comment] 2021-10-13 23:53
There is nothing else to post. The profile picture can be uploaded once, then I cannot delete it or replace it. Nothing happens when I click delete picture, and it just stays there. What else can I provide?

**Comment by acoolov** [comment] 2021-10-14 00:21
Steps to reproduce:

Go to the demo stable Yetiforce and try to delete the profile picture for the demo user (the Yeti logo). Nothing happens. The buttons don't do anything, delete, download, or zoom in. I just got one button to work once, and that's it. They don't work anymore, neither on my instance nor in the demo instance.

**Comment by rskrzypczak** [comment] 2021-10-14 02:46
As I mentioned, I don't see an error here, as you can see below.
So I close the issue because there is no way to reproduce the error.
Nevertheless, I suppose that one of the browser add-ons/extensions you have installed is blocking you from changing the photo.
Check on other browsers.
However, if you believe that the bug is native, please provide all the information mentioned by @mariuszkrzaczkowski.
![photoChange](https://user-images.githubusercontent.com/10221999/137241979-cf28981e-8946-4c8c-84f5-af4d94b49f16.gif)

**Closed as completed by rskrzypczak** 2021-10-14 02:46 UTC
Labels: 🤷‍♂️ MoreInfoRequired
