### ISSUE TITLE
[BUG] Quick create in calendar bug

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2340] opened 2015-11-27 21:39 UTC
![calendar_qc](https://cloud.githubusercontent.com/assets/4824588/11448397/8eeb977e-9557-11e5-97de-7279cbe18f4b.gif)

1. Fields not visible
2. After change to ToDo tab php error
3. Fields doesn't change to Event/ToDo specific fields (still the same)

**Comment by witer30** [comment] 2015-11-29 19:19
there are much more issues reported which are linked to calendar
#2242
#2241
#2236

**Comment by rskrzypczak** [comment] 2015-11-30 00:48
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/d70a08f4dd741173d2a492cfdc61a650c8a7db43

One topic per one issue.

**Closed by rskrzypczak** 2015-11-30 00:48 UTC
Labels: Priority::#3 High, Type::Bug

**Comment by bpabiszczak** [comment] 2015-11-30 01:24
The last screen is not a bug.

**Comment by witer30** [comment] 2015-11-30 15:13
Błażej, can you explained?
Strart time 9:00 and there is 9:11...?

**Comment by bpabiszczak** [comment] 2015-11-30 15:15
http://fullcalendar.io/docs/

**Comment by bpabiszczak** [comment] 2015-11-30 19:39
https://github.com/YetiForceCompany/YetiForceCRM/search?utf8=%E2%9C%93&q=slotMinutes

**Comment by witer30** [comment] 2015-12-01 09:37
Błażej, sorry do not agree it is a bug. Please see below:
1. case 
![image](https://cloud.githubusercontent.com/assets/11491482/11497119/230cd87a-9817-11e5-96f4-d5ee56bf8e34.png)
and cloud 
![image](https://cloud.githubusercontent.com/assets/11491482/11497129/30d7df18-9817-11e5-8d1f-7d9ee9c21512.png)
2 case
![image](https://cloud.githubusercontent.com/assets/11491482/11497149/52759264-9817-11e5-8d90-167735d3c4fb.png)
and cloud
![image](https://cloud.githubusercontent.com/assets/11491482/11497156/65b480ce-9817-11e5-90fd-305f0e78c9f1.png)

**Comment by bpabiszczak** [comment] 2015-12-01 13:38
The display format depends on the configuration fullcalendar.

**Comment by witer30** [comment] 2015-12-01 18:55
perfect, works greate thanks... 
can be closed
