### ISSUE TITLE
[bug] Natural sorting

### ISSUE THREAD

**Issue by fliszer** [YetiForceCompany/YetiForceCRM#14205] opened 2021-02-07 10:12 UTC
Is it possible to add / implement natural sorting (natsort in php) for filters? So the numbers will be sorted correctly. 
Simple example below:

![natural-sorting](https://user-images.githubusercontent.com/20444027/107143428-4fec4700-6935-11eb-846a-e4eaeb4828c7.png)

**Comment by rskrzypczak** [comment] 2021-02-07 18:04
It's not a bug (https://github.com/YetiForceCompany/YetiForceCRM/issues/13908) so I'm closing the ticket, but I'll remind you..
The sort method depends on the type of the column in the database. so.. if you mix up number and text, you can't get what you want ease.
I can quickly see two ways:
- divide the current name into several columns and sort by them. 
  I think this is the best solution and doesn't require any code changes.
- create a custom sort function in the database and use that function for this field, 
  but there are several reasons why you should not do this.

**Closed as completed by rskrzypczak** 2021-02-07 18:04 UTC
Labels: ❌ ignored

**Comment by diderich** [comment] 2021-02-08 11:21
There is an easy way to get the outcome you are looking for. Ensure that all numbers have the same length, if necessary preceding them with o e or more 0.

0001
0099
0123
1032
7018

**Comment by fliszer** [comment] 2021-02-08 11:56
@rskrzypczak, @diderich thanks for tips. I added extra column with (int) number.
