### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by vitt95** [YetiForceCompany/YetiForceCRM#16027] opened 2022-05-04 12:42 UTC
Hi, i'm trying to build some email models. In the email body I need to encorporate a link to external resorces. When I try to put link href , the email body parser deletes href attribute leaving an empty <a> tag. 

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |       6.3
| Web server (name and version)     |     apache / 2.4    |    
| PHP                                 |      7.4          |
| Browser (name and version)          |      Firefox          |
| Operating System (name and version) |     Ubuntu 20.04           |
| Database (name and version)         |     MySQL           |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment] 2022-05-04 12:46
Duplicate of #14263  #14924 #15208 #14263

**Closed as completed by mariuszkrzaczkowski** 2022-05-04 12:46 UTC
Labels: 🔙 duplicate

**Comment by s2b-git** [comment] 2022-06-22 08:17
[vitt95](https://github.com/vitt95) did you found solution / bug?
