### ISSUE TITLE
[bug] Price book permission do not work

### ISSUE THREAD

**Issue by leo719044** [YetiForceCompany/YetiForceCRM#15547] opened 2021-12-15 03:43 UTC
I created the price book, but it is always visible to all user who can access "price book" module (set in Module Access), no matter what permission set. also set it as "Private" 

🔥 How to trigger the error
Go to 'Price Book'
Create any price book
Set price book neither "Private" or not
See "Permission Inspector"
No matter what sharing rule, everyone(with Price book module access, set it Module access) can see "Price Book"
👷 Testing
 I confirm that I tested it at https://gitdeveloper.yetiforce.com/index.php?module=PriceBooks&view=Detail&record=2950&parent=118&mid=62
I changed the permission of Portal profile to see the prick book module.

📷 Screenshot of configuration
in profile seeting
![image](https://user-images.githubusercontent.com/88583995/146119027-f5f1d3bb-7aac-4494-9e7a-5f96e8998707.png)
Permission inspector
![image](https://user-images.githubusercontent.com/88583995/146119074-ed12e9a7-653a-4c89-aac3-d66b48937667.png)

🌍 Your Environment
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index

**Comment by mariuszkrzaczkowski** [comment] 2021-12-15 07:14
Duplicate of #15236

**Closed as completed by mariuszkrzaczkowski** 2021-12-15 07:14 UTC
