### ISSUE TITLE
Can not login to Roundcube --> Can not use Email module...SOS!! HELP

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#15] opened 2014-12-17 15:32 UTC
Hi all,
Thanks for YetiForce CRM! I used to use vtiger CRM for our business, so it's not difficult for me to use YetiForce CRM. But I can not login to Roundcube. Then can not active or setting Client Email or Outgoing mail server.
Can you tell me detail, step by step to setup Roundcube and mailscanner.
Thanks for all!

**Comment by bpabiszczak** [comment] 2015-01-26 12:13
We haven't received enough information about this issue, that's why we are closing it. If the problem appears in the future, please send us more detailed descriptions.

**Closed by bpabiszczak** 2015-01-26 12:13 UTC
Labels: question

**Comment by vinithsv** [comment] 2015-06-11 05:32
hai , i have an issue related to roundcube in yetiforce CRM . When i login using my exchange credentials its showing "Server Error: STATUS: Server Unavailable. 15". Is this related to my IMAP if so please let me know what changes i have to make in the Exchange server.
Thanks you

**Comment by gkArvindr** [comment] 2017-01-03 01:29
I See this error under Roundcube Log :
 OK - PEAR
ERROR - Net_SMTP | Failed to load Net/SMTP.php | http://pear.php.net/package/Net_SMTP
ERROR - Net_IDNA2 | Failed to load Net/IDNA2.php | http://pear.php.net/package/Net_IDNA2
ERROR - Mail_mime | Failed to load Mail/mime.php | http://pear.php.net/package/Mail_mime

Installed PHP Extension(s) and Application(s)
Module Name 	Version 	Actions
Auth_SASL 	1.0.6 	
Mail_Mime 	1.10.0 	
Net_IDNA2 	0.1.1 	
Net_SMTP 	1.7.2 	
Net_Socket 	1.0.14 

Where is that I am going wrong

**Comment by WalterLuis** [comment] 2017-01-03 09:16
One of the causes that has happened to me to be able to log in using a **Gmail** account is to change a setting related to my account that can be started in an unknown environment.

https://www.google.com/settings/security/lesssecureapps

If not, I was not allowed to log in
I hope you have solved it :D

**Comment by paula-w** [comment] 2017-01-03 09:49
@gkArvindr This is a server configuration issue, you have to contact your administrator and discuss it with him. We don’t provide this kind of support for free.
