### ISSUE TITLE
[bug] Auto assign bug

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#14605] opened 2021-04-27 14:43 UTC
please look at it:
https://github.com/YetiForceCompany/YetiForceCRM/issues/14544

**Comment by mariuszkrzaczkowski** [comment] 2021-04-27 20:50
Duplicate of #14544

**Closed as completed by mariuszkrzaczkowski** 2021-04-27 20:50 UTC
Labels: 🔙 duplicate

**Comment by rioshaz** [comment] 2021-04-28 07:12
any new son the solution brother ...
