### ISSUE TITLE
[BUG] Profiles

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1903] opened 2015-09-03 05:33 UTC
It does not work profile configuration, including for ordinary users, checked on the net installed version 2.2, you can not make the field read-only, it either disappears or is available for editing.

OBJECTIVE:
It is necessary that the user can modify the source of Secretary-treatment, and the user manager could only view it.
![animation 151](https://cloud.githubusercontent.com/assets/1402355/9651244/3a95e616-5227-11e5-8c52-c936d4456634.gif)

**Comment by vovpff** [comment] 2015-09-03 07:15
Let's try it with non admin user!

**Comment by waw555** [comment] 2015-09-03 08:03
It does not work profile configuration, including for ordinary users, checked on the net installed version 2.2, you can not make the field read-only, it either disappears or is available for editing.

**Comment by vovpff** [comment] 2015-09-03 08:36
I repaeted your actions but for Sales profile.
1) If I add new record by admin (Administrator profile) user I can see and change Lead Source field:
![image](https://cloud.githubusercontent.com/assets/8545791/9653842/fad35ad8-522e-11e5-843f-2e1f89f99446.png)
2) Lead Source field changed to read-only to Sales Profile.
3) If I try to add record by user assigned to Sales Profile there is not possible to add Lead Source value:
![image](https://cloud.githubusercontent.com/assets/8545791/9653901/7c8b3b9a-522f-11e5-86bc-f405bfbd0b1e.png)
But it visible for this user:
![image](https://cloud.githubusercontent.com/assets/8545791/9653933/b4221042-522f-11e5-89a8-e6bb916154c9.png)
I think this is not a bug because you try to use only only admin user. Try this with another non-admin user assigned to non-adin profile.

**Closed** 2015-10-05 22:01 UTC
Labels: Label::Logic, Priority::#2 Normal, Type::Wontfix
