### ISSUE TITLE
Activation

### ISSUE THREAD

**Issue by Jenright240** [YetiForceCompany/YetiForceCRM#17319] opened 2023-11-01 12:14 UTC
Now matter which way I add my company info I keep getting incorrect data status for activation. 

My company as the provider as I'm installing the software for my friends company and I have his company listed as the end user. All the info 8s correct so why does it keep going to incorrect data status?

**Comment by Marco31Bike** [comment] 2023-11-01 13:04
Registration should be simplified. Confirmation of registration via email link would besufficient. At the moment it looks a bit too strict and causing lots of disappointment: 
https://github.com/YetiForceCompany/YetiForceCRM/discussions/17311

**Comment by paula-w** [comment] 2023-11-06 13:59
@Jenright240 usually the "Entity's Unique ID" is what causes the registration to be marked as incorrect, but please send your APP ID to registration@yetiforce.com, we'll check what the issue is.

**Closed as completed by paula-w** 2023-11-06 13:59 UTC

**Comment by Jenright240** [comment] 2023-11-06 14:06
Here is the AppID

****

**Comment by paula-w** [comment] 2023-11-06 14:18
> All the info 8s correct so why does it keep going to incorrect data status?

The Entity's Unique ID is incorrect.
You can find what to enter in the registration fields in [our documentation](https://doc.yetiforce.com/administrator-guides/company/company-details/#entitys-unique-identifier).

**Comment by Jenright240** [comment] 2023-11-06 14:30
Enright: 339724853 should be used then for both

**Comment by paula-w** [comment] 2023-11-06 14:47
I'm going to delete your post because this is sensitive information that probably shouldn't be on a public forum. 
Additionally, you need to fix the Entity ID in your system, I can't do it on your behalf - take a look at the link I included in my previous post, there's a tutorial at the top of the page on how to register.

**Comment by VictorTWB** [comment] 2023-11-24 03:41
Same Issue here. Activation was successful but the incorrect data error comes on after a day.

**Comment by paula-w** [comment] 2023-11-24 08:48
The error is pretty self-explanatory. You provided incorrect data and your registration was rejected. The solution is described in this thread.
